### ISSUE TITLE
There is no admin output for this module

### ISSUE THREAD

**Issue by phucleduy** [dylanhansch/whmcs-order-management#14]
"There is no admin output for this module" even though I have installed admin rights
![image](https://user-images.githubusercontent.com/66020266/83581672-b41a6800-a569-11ea-8436-8764ef9549c4.png)

**Comment by dylanhansch** [comment]
@phucleduy I don’t understand what the issue is.

**Comment by phucleduy** [comment]
plz help me. Tks!
![image](https://user-images.githubusercontent.com/66020266/83589351-bbe40780-a57d-11ea-9d29-7440be703ece.png)

**Comment by dylanhansch** [comment]
@phucleduy There isn't supposed to be admin output.

**Comment by phucleduy** [comment]
How do I fix it?

**Comment by dylanhansch** [comment]
@phucleduy There is nothing to fix.

**Comment by phucleduy** [comment]
tks u <3
