### ISSUE TITLE
Better logging of module actions

### ISSUE THREAD

**Issue by dylanhansch** [dylanhansch/whmcs-order-management#3]
It's hard to sift through the module logs especially on WHMCS installations with loads of other module actions if there's no way to sort out which entries are from this module. Makes debugging difficult (e.g. to figure out why an invoice was or wasn't cancelled)

**Comment by Octolus** [comment]
Any updates planned? This is an excellent module!

**Comment by dylanhansch** [comment]
@Octolus, thank you! I've been super busy with some other projects lately, but when I find some time I do plan on getting through these issues and improving the code a bit.
