### ISSUE TITLE
No admin panel

### ISSUE THREAD

**Issue by ghost** [dylanhansch/whmcs-order-management#6]
When going to the following page (/admin/addonmodules.php?module=order_management), I get this error message:

"There is no admin output for this module"

**Comment by dylanhansch** [comment]
This is expected and not an issue.

**Comment by ghost** [comment]
Is this excepted because the addon no longer works or am I missing something here?

**Comment by dylanhansch** [comment]
I don't see the issue. There is no "admin panel" for this module.

The addon still works.

**Comment by ghost** [comment]
Hi Dylan,

I've just checked and tested myself and all is working. Just a misunderstanding...

Thanks a lot.
