### ISSUE TITLE
Option to enable/disable specific tasks

### ISSUE THREAD

**Issue by dylanhansch** [dylanhansch/whmcs-order-management#7]
Add ability to enable/disable specific tasks (e.g. accept pending but paid orders)

**Comment by bgf2** [comment]
good thing, 
also add option to cancel the invoice when the terminate button is pushed.

**Comment by dylanhansch** [comment]
> also add option to cancel the invoice when the terminate button is pushed.

Thanks for the suggestion! I'll look into adding this in the future as part of a different feature request.
