### ISSUE TITLE
Not an issue, but a quesiton

### ISSUE THREAD

**Issue by shabsta** [dylanhansch/whmcs-order-management#9]
Is it possible to change the amount days after which an invoice / order can be cancelled?

Does the auto accept order work with clients who have passed fraud checks, ie orders where the client already have services and whmcs automatically provisions these services dependent on how whmcs's automation settings are defined?

**Comment by dylanhansch** [comment]
> Is it possible to change the amount days after which an invoice / order can be cancelled?

Yes, this can be done from the module config page.

> Does the auto accept order work with clients who have passed fraud checks, ie orders where the client already have services and whmcs automatically provisions these services dependent on how whmcs's automation settings are defined?

Yes (if I understand your situation correctly, it's similar to my own).
